# Generated by Django 5.2 on 2026-05-27 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP CSV Export'), ('UTILITY', 'Utility Portal CSV Export'), ('TRAVEL', 'Travel (Concur/Navan) CSV Export')], max_length=20)),
                ('name', models.CharField(help_text='Human-readable name for this source', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_mapping', models.JSONField(default=dict, help_text='CSV column to normalized field mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingest_data_source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_csv_content', models.TextField(help_text='Original CSV file content as text (never modified, source of truth)')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA256 hash for idempotency', max_length=64, unique=True)),
                ('line_count', models.IntegerField(help_text='Number of rows in file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestions', to='ingest.datasource')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingestions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingest_raw_ingestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_number', models.IntegerField()),
                ('raw_values', models.JSONField()),
                ('parsing_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_records', to='tenants.tenant')),
                ('ingestion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_records', to='ingest.rawingestion')),
            ],
            options={
                'db_table': 'ingest_parsed_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('scope_1_emissions', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('scope_2_emissions', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('scope_3_emissions', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('reporting_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data_quality_score', models.IntegerField(default=0, help_text='0-100 quality score')),
                ('normalized_values', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('data_quality_flags', models.JSONField(default=list)),
                ('is_valid', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant')),
                ('parsed_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingest.parsedrecord')),
                ('ingestion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingest.rawingestion')),
            ],
            options={
                'db_table': 'ingest_normalized_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant_id'], name='ingest_data_tenant__4fbc01_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['source_type'], name='ingest_data_source__4aa952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['tenant_id'], name='ingest_raw__tenant__857f32_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['data_source_id'], name='ingest_raw__data_so_e8ae73_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['file_hash'], name='ingest_raw__file_ha_52e075_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedrecord',
            index=models.Index(fields=['ingestion_id'], name='ingest_pars_ingesti_b862f2_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedrecord',
            index=models.Index(fields=['tenant_id'], name='ingest_pars_tenant__8283a6_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedrecord',
            index=models.Index(fields=['source_row_number'], name='ingest_pars_source__6de33b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parsedrecord',
            unique_together={('ingestion_id', 'source_row_number')},
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['ingestion_id'], name='ingest_norm_ingesti_7af617_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant_id'], name='ingest_norm_tenant__0da359_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['is_valid'], name='ingest_norm_is_vali_41e99d_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['facility_name', 'reporting_year'], name='ingest_norm_facilit_fbe043_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normalizedrecord',
            unique_together={('ingestion_id', 'parsed_record_id')},
        ),
    ]
