# Generated by Django 5.2 on 2026-05-27 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(db_index=True, help_text='Type of object: EmissionsDataPoint, ReviewTask, NormalizedRecord', max_length=50)),
                ('object_id', models.CharField(db_index=True, help_text='UUID of the object being audited', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Record created'), ('UPDATE', 'Record updated'), ('DELETE', 'Record deleted')], db_index=True, max_length=10)),
                ('change_summary', models.JSONField(default=dict, help_text="JSON: {'old_values': {...}, 'new_values': {...}}")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.CharField(blank=True, help_text='IPv4 (15 chars) or IPv6 (45 chars)', max_length=45, null=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
                ('user_id', models.ForeignKey(blank=True, help_text='User who triggered the change (null=system action)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant_id'], name='audit_audit_tenant__344ac2_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__26da80_idx'), models.Index(fields=['action'], name='audit_audit_action_e47115_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_1915b1_idx'), models.Index(fields=['user_id'], name='audit_audit_user_id_63c1a3_idx')],
            },
        ),
    ]
