# Generated by Django 5.2 on 2026-05-27 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting review'), ('APPROVED', 'Approved by analyst'), ('REJECTED', 'Rejected by analyst'), ('PENDING_CHANGES', 'Awaiting re-submission')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low priority'), ('MEDIUM', 'Medium priority'), ('HIGH', 'High priority (missing critical data)')], default='MEDIUM', max_length=10)),
                ('reason_codes', models.JSONField(default=list, help_text="Codes explaining why review is needed: ['validation_error', 'low_quality', 'auto_flag']")),
                ('analyst_notes', models.TextField(blank=True, help_text='Notes from analyst during review', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Why was this rejected?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_review_tasks', to=settings.AUTH_USER_MODEL)),
                ('ingestion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='ingest.rawingestion')),
                ('normalized_record_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_task', to='ingest.normalizedrecord')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_review_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_review_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved for analytics'), ('REJECTED', 'Rejected, request re-submission'), ('FLAG_FOR_EXPERT', 'Flag for expert review')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_approvals', to='tenants.tenant')),
                ('review_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='review.reviewtask')),
            ],
            options={
                'db_table': 'review_review_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['tenant_id'], name='review_revi_tenant__364bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['status'], name='review_revi_status_57632d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['priority'], name='review_revi_priorit_baf668_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['ingestion_id'], name='review_revi_ingesti_dd5455_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewapproval',
            index=models.Index(fields=['tenant_id'], name='review_revi_tenant__db3d87_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewapproval',
            index=models.Index(fields=['decision'], name='review_revi_decisio_7d1aa7_idx'),
        ),
    ]
