# Generated by Django 5.2 on 2026-05-27 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionsDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(db_index=True, max_length=255)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1: Direct emissions'), ('SCOPE_2', 'Scope 2: Indirect (electricity, steam)'), ('SCOPE_3', 'Scope 3: Value chain')], db_index=True, max_length=20)),
                ('emissions_value', models.DecimalField(decimal_places=4, help_text='Numeric emissions value', max_digits=15)),
                ('emissions_unit', models.CharField(choices=[('mtCO2e', 'Metric tons CO2 equivalent'), ('tCO2e', 'Tons CO2 equivalent'), ('kgCO2e', 'Kilograms CO2 equivalent')], default='mtCO2e', max_length=20)),
                ('year', models.IntegerField(db_index=True, help_text='Reporting year')),
                ('methodology', models.CharField(blank=True, help_text='Calculation methodology', max_length=255, null=True)),
                ('is_valid', models.BooleanField(db_index=True, default=False, help_text='Passed all validation checks')),
                ('normalized_values', models.JSONField(default=dict, help_text='Complete normalized data as JSON')),
                ('validation_errors', models.JSONField(default=list, help_text='List of validation failures')),
                ('data_quality_flags', models.JSONField(default=list, help_text='Quality warnings and issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions_data_points', to='ingest.datasource')),
                ('parsed_record_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissions_data_points', to='ingest.parsedrecord')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions_data_points', to='tenants.tenant')),
            ],
            options={
                'db_table': 'emissions_emissions_data_point',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='emissions_e_tenant__228eaf_idx'), models.Index(fields=['data_source_id'], name='emissions_e_data_so_bf757b_idx'), models.Index(fields=['facility_name', 'year'], name='emissions_e_facilit_f09ea9_idx'), models.Index(fields=['is_valid', 'year'], name='emissions_e_is_vali_98f27a_idx')],
            },
        ),
    ]
